source_dir: /Users/allwefantasy/projects/auto-coder
target_file: /Users/allwefantasy/projects/auto-coder/output.txt 
project_type: py

model: qwen110b_chat
index_model: qwen110b_chat
emb_model: gpt_emb

index_filter_level: 1
index_model_max_input_length: 30000
index_filter_workers: 4
index_build_workers: 4

# enable_rag_context: true

skip_build_index: false
execute: true
## 代码生成的时候会每次生成一个文件，现在大模型无法一次性生成太多文件，所以需要多轮生成
enable_multi_round_generate: true
auto_merge: true
human_as_model: true 